#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCONGVAN
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCV")]
	public partial class QLCVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCONGVAN(CONGVAN instance);
    partial void UpdateCONGVAN(CONGVAN instance);
    partial void DeleteCONGVAN(CONGVAN instance);
    partial void InsertCOQUAN(COQUAN instance);
    partial void UpdateCOQUAN(COQUAN instance);
    partial void DeleteCOQUAN(COQUAN instance);
    partial void InsertDANGNHAP(DANGNHAP instance);
    partial void UpdateDANGNHAP(DANGNHAP instance);
    partial void DeleteDANGNHAP(DANGNHAP instance);
    partial void InsertLOAICONGVAN(LOAICONGVAN instance);
    partial void UpdateLOAICONGVAN(LOAICONGVAN instance);
    partial void DeleteLOAICONGVAN(LOAICONGVAN instance);
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    partial void InsertPHANQUYEN(PHANQUYEN instance);
    partial void UpdatePHANQUYEN(PHANQUYEN instance);
    partial void DeletePHANQUYEN(PHANQUYEN instance);
    partial void InsertPHONGBAN(PHONGBAN instance);
    partial void UpdatePHONGBAN(PHONGBAN instance);
    partial void DeletePHONGBAN(PHONGBAN instance);
    #endregion
		
		public QLCVDataContext() : 
				base(global::QLCONGVAN.Properties.Settings.Default.QLCVConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLCVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CONGVAN> CONGVANs
		{
			get
			{
				return this.GetTable<CONGVAN>();
			}
		}
		
		public System.Data.Linq.Table<COQUAN> COQUANs
		{
			get
			{
				return this.GetTable<COQUAN>();
			}
		}
		
		public System.Data.Linq.Table<DANGNHAP> DANGNHAPs
		{
			get
			{
				return this.GetTable<DANGNHAP>();
			}
		}
		
		public System.Data.Linq.Table<LOAICONGVAN> LOAICONGVANs
		{
			get
			{
				return this.GetTable<LOAICONGVAN>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this.GetTable<PHANQUYEN>();
			}
		}
		
		public System.Data.Linq.Table<PHONGBAN> PHONGBANs
		{
			get
			{
				return this.GetTable<PHONGBAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONGVAN")]
	public partial class CONGVAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCV;
		
		private string _maCQ;
		
		private string _maPB;
		
		private string _maND;
		
		private string _maLoaiCV;
		
		private string _soCongVan;
		
		private string _tieuDe;
		
		private string _trichNoiDung;
		
		private System.Nullable<System.DateTime> _ngayTao;
		
		private System.Nullable<System.DateTime> _ngayCapNhat;
		
		private string _trangThai;
		
		private string _nguoiTao;
		
		private string _nguoiXuLy;
		
		private string _nguoiPheDuyet;
		
		private string _mucDoKhanCap;
		
		private string _noiNhan;
		
		private string _tepDinhKem;
		
		private EntityRef<COQUAN> _COQUAN;
		
		private EntityRef<LOAICONGVAN> _LOAICONGVAN;
		
		private EntityRef<NGUOIDUNG> _NGUOIDUNG;
		
		private EntityRef<PHONGBAN> _PHONGBAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCVChanging(string value);
    partial void OnmaCVChanged();
    partial void OnmaCQChanging(string value);
    partial void OnmaCQChanged();
    partial void OnmaPBChanging(string value);
    partial void OnmaPBChanged();
    partial void OnmaNDChanging(string value);
    partial void OnmaNDChanged();
    partial void OnmaLoaiCVChanging(string value);
    partial void OnmaLoaiCVChanged();
    partial void OnsoCongVanChanging(string value);
    partial void OnsoCongVanChanged();
    partial void OntieuDeChanging(string value);
    partial void OntieuDeChanged();
    partial void OntrichNoiDungChanging(string value);
    partial void OntrichNoiDungChanged();
    partial void OnngayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTaoChanged();
    partial void OnngayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngayCapNhatChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnnguoiTaoChanging(string value);
    partial void OnnguoiTaoChanged();
    partial void OnnguoiXuLyChanging(string value);
    partial void OnnguoiXuLyChanged();
    partial void OnnguoiPheDuyetChanging(string value);
    partial void OnnguoiPheDuyetChanged();
    partial void OnmucDoKhanCapChanging(string value);
    partial void OnmucDoKhanCapChanged();
    partial void OnnoiNhanChanging(string value);
    partial void OnnoiNhanChanged();
    partial void OntepDinhKemChanging(string value);
    partial void OntepDinhKemChanged();
    #endregion
		
		public CONGVAN()
		{
			this._COQUAN = default(EntityRef<COQUAN>);
			this._LOAICONGVAN = default(EntityRef<LOAICONGVAN>);
			this._NGUOIDUNG = default(EntityRef<NGUOIDUNG>);
			this._PHONGBAN = default(EntityRef<PHONGBAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCV
		{
			get
			{
				return this._maCV;
			}
			set
			{
				if ((this._maCV != value))
				{
					this.OnmaCVChanging(value);
					this.SendPropertyChanging();
					this._maCV = value;
					this.SendPropertyChanged("maCV");
					this.OnmaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCQ", DbType="VarChar(10)")]
		public string maCQ
		{
			get
			{
				return this._maCQ;
			}
			set
			{
				if ((this._maCQ != value))
				{
					if (this._COQUAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCQChanging(value);
					this.SendPropertyChanging();
					this._maCQ = value;
					this.SendPropertyChanged("maCQ");
					this.OnmaCQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPB", DbType="VarChar(10)")]
		public string maPB
		{
			get
			{
				return this._maPB;
			}
			set
			{
				if ((this._maPB != value))
				{
					if (this._PHONGBAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPBChanging(value);
					this.SendPropertyChanging();
					this._maPB = value;
					this.SendPropertyChanged("maPB");
					this.OnmaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maND", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string maND
		{
			get
			{
				return this._maND;
			}
			set
			{
				if ((this._maND != value))
				{
					if (this._NGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNDChanging(value);
					this.SendPropertyChanging();
					this._maND = value;
					this.SendPropertyChanged("maND");
					this.OnmaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiCV", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string maLoaiCV
		{
			get
			{
				return this._maLoaiCV;
			}
			set
			{
				if ((this._maLoaiCV != value))
				{
					if (this._LOAICONGVAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiCVChanging(value);
					this.SendPropertyChanging();
					this._maLoaiCV = value;
					this.SendPropertyChanged("maLoaiCV");
					this.OnmaLoaiCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCongVan", DbType="VarChar(50)")]
		public string soCongVan
		{
			get
			{
				return this._soCongVan;
			}
			set
			{
				if ((this._soCongVan != value))
				{
					this.OnsoCongVanChanging(value);
					this.SendPropertyChanging();
					this._soCongVan = value;
					this.SendPropertyChanged("soCongVan");
					this.OnsoCongVanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieuDe", DbType="NVarChar(255)")]
		public string tieuDe
		{
			get
			{
				return this._tieuDe;
			}
			set
			{
				if ((this._tieuDe != value))
				{
					this.OntieuDeChanging(value);
					this.SendPropertyChanging();
					this._tieuDe = value;
					this.SendPropertyChanged("tieuDe");
					this.OntieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trichNoiDung", DbType="NVarChar(255)")]
		public string trichNoiDung
		{
			get
			{
				return this._trichNoiDung;
			}
			set
			{
				if ((this._trichNoiDung != value))
				{
					this.OntrichNoiDungChanging(value);
					this.SendPropertyChanging();
					this._trichNoiDung = value;
					this.SendPropertyChanged("trichNoiDung");
					this.OntrichNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTao", DbType="Date")]
		public System.Nullable<System.DateTime> ngayTao
		{
			get
			{
				return this._ngayTao;
			}
			set
			{
				if ((this._ngayTao != value))
				{
					this.OnngayTaoChanging(value);
					this.SendPropertyChanging();
					this._ngayTao = value;
					this.SendPropertyChanged("ngayTao");
					this.OnngayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCapNhat", DbType="Date")]
		public System.Nullable<System.DateTime> ngayCapNhat
		{
			get
			{
				return this._ngayCapNhat;
			}
			set
			{
				if ((this._ngayCapNhat != value))
				{
					this.OnngayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._ngayCapNhat = value;
					this.SendPropertyChanged("ngayCapNhat");
					this.OnngayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50)")]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiTao", DbType="NVarChar(255)")]
		public string nguoiTao
		{
			get
			{
				return this._nguoiTao;
			}
			set
			{
				if ((this._nguoiTao != value))
				{
					this.OnnguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._nguoiTao = value;
					this.SendPropertyChanged("nguoiTao");
					this.OnnguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiXuLy", DbType="NVarChar(255)")]
		public string nguoiXuLy
		{
			get
			{
				return this._nguoiXuLy;
			}
			set
			{
				if ((this._nguoiXuLy != value))
				{
					this.OnnguoiXuLyChanging(value);
					this.SendPropertyChanging();
					this._nguoiXuLy = value;
					this.SendPropertyChanged("nguoiXuLy");
					this.OnnguoiXuLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiPheDuyet", DbType="NVarChar(255)")]
		public string nguoiPheDuyet
		{
			get
			{
				return this._nguoiPheDuyet;
			}
			set
			{
				if ((this._nguoiPheDuyet != value))
				{
					this.OnnguoiPheDuyetChanging(value);
					this.SendPropertyChanging();
					this._nguoiPheDuyet = value;
					this.SendPropertyChanged("nguoiPheDuyet");
					this.OnnguoiPheDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mucDoKhanCap", DbType="NVarChar(50)")]
		public string mucDoKhanCap
		{
			get
			{
				return this._mucDoKhanCap;
			}
			set
			{
				if ((this._mucDoKhanCap != value))
				{
					this.OnmucDoKhanCapChanging(value);
					this.SendPropertyChanging();
					this._mucDoKhanCap = value;
					this.SendPropertyChanged("mucDoKhanCap");
					this.OnmucDoKhanCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiNhan", DbType="NVarChar(255)")]
		public string noiNhan
		{
			get
			{
				return this._noiNhan;
			}
			set
			{
				if ((this._noiNhan != value))
				{
					this.OnnoiNhanChanging(value);
					this.SendPropertyChanging();
					this._noiNhan = value;
					this.SendPropertyChanged("noiNhan");
					this.OnnoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tepDinhKem", DbType="NVarChar(255)")]
		public string tepDinhKem
		{
			get
			{
				return this._tepDinhKem;
			}
			set
			{
				if ((this._tepDinhKem != value))
				{
					this.OntepDinhKemChanging(value);
					this.SendPropertyChanging();
					this._tepDinhKem = value;
					this.SendPropertyChanged("tepDinhKem");
					this.OntepDinhKemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COQUAN_CONGVAN", Storage="_COQUAN", ThisKey="maCQ", OtherKey="maCQ", IsForeignKey=true)]
		public COQUAN COQUAN
		{
			get
			{
				return this._COQUAN.Entity;
			}
			set
			{
				COQUAN previousValue = this._COQUAN.Entity;
				if (((previousValue != value) 
							|| (this._COQUAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COQUAN.Entity = null;
						previousValue.CONGVANs.Remove(this);
					}
					this._COQUAN.Entity = value;
					if ((value != null))
					{
						value.CONGVANs.Add(this);
						this._maCQ = value.maCQ;
					}
					else
					{
						this._maCQ = default(string);
					}
					this.SendPropertyChanged("COQUAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAICONGVAN_CONGVAN", Storage="_LOAICONGVAN", ThisKey="maLoaiCV", OtherKey="maLoaiCV", IsForeignKey=true)]
		public LOAICONGVAN LOAICONGVAN
		{
			get
			{
				return this._LOAICONGVAN.Entity;
			}
			set
			{
				LOAICONGVAN previousValue = this._LOAICONGVAN.Entity;
				if (((previousValue != value) 
							|| (this._LOAICONGVAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAICONGVAN.Entity = null;
						previousValue.CONGVANs.Remove(this);
					}
					this._LOAICONGVAN.Entity = value;
					if ((value != null))
					{
						value.CONGVANs.Add(this);
						this._maLoaiCV = value.maLoaiCV;
					}
					else
					{
						this._maLoaiCV = default(string);
					}
					this.SendPropertyChanged("LOAICONGVAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_CONGVAN", Storage="_NGUOIDUNG", ThisKey="maND", OtherKey="maND", IsForeignKey=true)]
		public NGUOIDUNG NGUOIDUNG
		{
			get
			{
				return this._NGUOIDUNG.Entity;
			}
			set
			{
				NGUOIDUNG previousValue = this._NGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDUNG.Entity = null;
						previousValue.CONGVANs.Remove(this);
					}
					this._NGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.CONGVANs.Add(this);
						this._maND = value.maND;
					}
					else
					{
						this._maND = default(string);
					}
					this.SendPropertyChanged("NGUOIDUNG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGBAN_CONGVAN", Storage="_PHONGBAN", ThisKey="maPB", OtherKey="maPB", IsForeignKey=true)]
		public PHONGBAN PHONGBAN
		{
			get
			{
				return this._PHONGBAN.Entity;
			}
			set
			{
				PHONGBAN previousValue = this._PHONGBAN.Entity;
				if (((previousValue != value) 
							|| (this._PHONGBAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGBAN.Entity = null;
						previousValue.CONGVANs.Remove(this);
					}
					this._PHONGBAN.Entity = value;
					if ((value != null))
					{
						value.CONGVANs.Add(this);
						this._maPB = value.maPB;
					}
					else
					{
						this._maPB = default(string);
					}
					this.SendPropertyChanged("PHONGBAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COQUAN")]
	public partial class COQUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCQ;
		
		private string _tenCQ;
		
		private string _diaChi;
		
		private string _sdt;
		
		private EntitySet<CONGVAN> _CONGVANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCQChanging(string value);
    partial void OnmaCQChanged();
    partial void OntenCQChanging(string value);
    partial void OntenCQChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    #endregion
		
		public COQUAN()
		{
			this._CONGVANs = new EntitySet<CONGVAN>(new Action<CONGVAN>(this.attach_CONGVANs), new Action<CONGVAN>(this.detach_CONGVANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCQ", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCQ
		{
			get
			{
				return this._maCQ;
			}
			set
			{
				if ((this._maCQ != value))
				{
					this.OnmaCQChanging(value);
					this.SendPropertyChanging();
					this._maCQ = value;
					this.SendPropertyChanged("maCQ");
					this.OnmaCQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCQ", DbType="NVarChar(100)")]
		public string tenCQ
		{
			get
			{
				return this._tenCQ;
			}
			set
			{
				if ((this._tenCQ != value))
				{
					this.OntenCQChanging(value);
					this.SendPropertyChanging();
					this._tenCQ = value;
					this.SendPropertyChanged("tenCQ");
					this.OntenCQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(200)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NVarChar(15)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COQUAN_CONGVAN", Storage="_CONGVANs", ThisKey="maCQ", OtherKey="maCQ")]
		public EntitySet<CONGVAN> CONGVANs
		{
			get
			{
				return this._CONGVANs;
			}
			set
			{
				this._CONGVANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONGVANs(CONGVAN entity)
		{
			this.SendPropertyChanging();
			entity.COQUAN = this;
		}
		
		private void detach_CONGVANs(CONGVAN entity)
		{
			this.SendPropertyChanging();
			entity.COQUAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANGNHAP")]
	public partial class DANGNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tenDangNhap;
		
		private string _matKhau;
		
		private EntitySet<NGUOIDUNG> _NGUOIDUNGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntenDangNhapChanging(string value);
    partial void OntenDangNhapChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    #endregion
		
		public DANGNHAP()
		{
			this._NGUOIDUNGs = new EntitySet<NGUOIDUNG>(new Action<NGUOIDUNG>(this.attach_NGUOIDUNGs), new Action<NGUOIDUNG>(this.detach_NGUOIDUNGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDangNhap", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tenDangNhap
		{
			get
			{
				return this._tenDangNhap;
			}
			set
			{
				if ((this._tenDangNhap != value))
				{
					this.OntenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._tenDangNhap = value;
					this.SendPropertyChanged("tenDangNhap");
					this.OntenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(100)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANGNHAP_NGUOIDUNG", Storage="_NGUOIDUNGs", ThisKey="tenDangNhap", OtherKey="tenDangNhap")]
		public EntitySet<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this._NGUOIDUNGs;
			}
			set
			{
				this._NGUOIDUNGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.DANGNHAP = this;
		}
		
		private void detach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.DANGNHAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAICONGVAN")]
	public partial class LOAICONGVAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoaiCV;
		
		private string _tenLoai;
		
		private string _moTa;
		
		private EntitySet<CONGVAN> _CONGVANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiCVChanging(string value);
    partial void OnmaLoaiCVChanged();
    partial void OntenLoaiChanging(string value);
    partial void OntenLoaiChanged();
    partial void OnmoTaChanging(string value);
    partial void OnmoTaChanged();
    #endregion
		
		public LOAICONGVAN()
		{
			this._CONGVANs = new EntitySet<CONGVAN>(new Action<CONGVAN>(this.attach_CONGVANs), new Action<CONGVAN>(this.detach_CONGVANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiCV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoaiCV
		{
			get
			{
				return this._maLoaiCV;
			}
			set
			{
				if ((this._maLoaiCV != value))
				{
					this.OnmaLoaiCVChanging(value);
					this.SendPropertyChanging();
					this._maLoaiCV = value;
					this.SendPropertyChanged("maLoaiCV");
					this.OnmaLoaiCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoai", DbType="NVarChar(255)")]
		public string tenLoai
		{
			get
			{
				return this._tenLoai;
			}
			set
			{
				if ((this._tenLoai != value))
				{
					this.OntenLoaiChanging(value);
					this.SendPropertyChanging();
					this._tenLoai = value;
					this.SendPropertyChanged("tenLoai");
					this.OntenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="NVarChar(255)")]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this.OnmoTaChanging(value);
					this.SendPropertyChanging();
					this._moTa = value;
					this.SendPropertyChanged("moTa");
					this.OnmoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAICONGVAN_CONGVAN", Storage="_CONGVANs", ThisKey="maLoaiCV", OtherKey="maLoaiCV")]
		public EntitySet<CONGVAN> CONGVANs
		{
			get
			{
				return this._CONGVANs;
			}
			set
			{
				this._CONGVANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONGVANs(CONGVAN entity)
		{
			this.SendPropertyChanging();
			entity.LOAICONGVAN = this;
		}
		
		private void detach_CONGVANs(CONGVAN entity)
		{
			this.SendPropertyChanging();
			entity.LOAICONGVAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maND;
		
		private string _maQuyen;
		
		private string _hoTen;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _ngayTao;
		
		private string _trangThai;
		
		private string _sdt;
		
		private string _tenDangNhap;
		
		private EntitySet<CONGVAN> _CONGVANs;
		
		private EntityRef<DANGNHAP> _DANGNHAP;
		
		private EntityRef<PHANQUYEN> _PHANQUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNDChanging(string value);
    partial void OnmaNDChanged();
    partial void OnmaQuyenChanging(string value);
    partial void OnmaQuyenChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnngayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTaoChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OntenDangNhapChanging(string value);
    partial void OntenDangNhapChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			this._CONGVANs = new EntitySet<CONGVAN>(new Action<CONGVAN>(this.attach_CONGVANs), new Action<CONGVAN>(this.detach_CONGVANs));
			this._DANGNHAP = default(EntityRef<DANGNHAP>);
			this._PHANQUYEN = default(EntityRef<PHANQUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maND", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maND
		{
			get
			{
				return this._maND;
			}
			set
			{
				if ((this._maND != value))
				{
					this.OnmaNDChanging(value);
					this.SendPropertyChanging();
					this._maND = value;
					this.SendPropertyChanged("maND");
					this.OnmaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maQuyen", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string maQuyen
		{
			get
			{
				return this._maQuyen;
			}
			set
			{
				if ((this._maQuyen != value))
				{
					if (this._PHANQUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaQuyenChanging(value);
					this.SendPropertyChanging();
					this._maQuyen = value;
					this.SendPropertyChanged("maQuyen");
					this.OnmaQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(255)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTao", DbType="Date")]
		public System.Nullable<System.DateTime> ngayTao
		{
			get
			{
				return this._ngayTao;
			}
			set
			{
				if ((this._ngayTao != value))
				{
					this.OnngayTaoChanging(value);
					this.SendPropertyChanging();
					this._ngayTao = value;
					this.SendPropertyChanged("ngayTao");
					this.OnngayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50)")]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(15)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDangNhap", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenDangNhap
		{
			get
			{
				return this._tenDangNhap;
			}
			set
			{
				if ((this._tenDangNhap != value))
				{
					if (this._DANGNHAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._tenDangNhap = value;
					this.SendPropertyChanged("tenDangNhap");
					this.OntenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_CONGVAN", Storage="_CONGVANs", ThisKey="maND", OtherKey="maND")]
		public EntitySet<CONGVAN> CONGVANs
		{
			get
			{
				return this._CONGVANs;
			}
			set
			{
				this._CONGVANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANGNHAP_NGUOIDUNG", Storage="_DANGNHAP", ThisKey="tenDangNhap", OtherKey="tenDangNhap", IsForeignKey=true)]
		public DANGNHAP DANGNHAP
		{
			get
			{
				return this._DANGNHAP.Entity;
			}
			set
			{
				DANGNHAP previousValue = this._DANGNHAP.Entity;
				if (((previousValue != value) 
							|| (this._DANGNHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANGNHAP.Entity = null;
						previousValue.NGUOIDUNGs.Remove(this);
					}
					this._DANGNHAP.Entity = value;
					if ((value != null))
					{
						value.NGUOIDUNGs.Add(this);
						this._tenDangNhap = value.tenDangNhap;
					}
					else
					{
						this._tenDangNhap = default(string);
					}
					this.SendPropertyChanged("DANGNHAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANQUYEN_NGUOIDUNG", Storage="_PHANQUYEN", ThisKey="maQuyen", OtherKey="maQuyen", IsForeignKey=true)]
		public PHANQUYEN PHANQUYEN
		{
			get
			{
				return this._PHANQUYEN.Entity;
			}
			set
			{
				PHANQUYEN previousValue = this._PHANQUYEN.Entity;
				if (((previousValue != value) 
							|| (this._PHANQUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHANQUYEN.Entity = null;
						previousValue.NGUOIDUNGs.Remove(this);
					}
					this._PHANQUYEN.Entity = value;
					if ((value != null))
					{
						value.NGUOIDUNGs.Add(this);
						this._maQuyen = value.maQuyen;
					}
					else
					{
						this._maQuyen = default(string);
					}
					this.SendPropertyChanged("PHANQUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONGVANs(CONGVAN entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = this;
		}
		
		private void detach_CONGVANs(CONGVAN entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANQUYEN")]
	public partial class PHANQUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maQuyen;
		
		private string _tenQuyen;
		
		private string _moTa;
		
		private EntitySet<NGUOIDUNG> _NGUOIDUNGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaQuyenChanging(string value);
    partial void OnmaQuyenChanged();
    partial void OntenQuyenChanging(string value);
    partial void OntenQuyenChanged();
    partial void OnmoTaChanging(string value);
    partial void OnmoTaChanged();
    #endregion
		
		public PHANQUYEN()
		{
			this._NGUOIDUNGs = new EntitySet<NGUOIDUNG>(new Action<NGUOIDUNG>(this.attach_NGUOIDUNGs), new Action<NGUOIDUNG>(this.detach_NGUOIDUNGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maQuyen", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maQuyen
		{
			get
			{
				return this._maQuyen;
			}
			set
			{
				if ((this._maQuyen != value))
				{
					this.OnmaQuyenChanging(value);
					this.SendPropertyChanging();
					this._maQuyen = value;
					this.SendPropertyChanged("maQuyen");
					this.OnmaQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenQuyen", DbType="NVarChar(255)")]
		public string tenQuyen
		{
			get
			{
				return this._tenQuyen;
			}
			set
			{
				if ((this._tenQuyen != value))
				{
					this.OntenQuyenChanging(value);
					this.SendPropertyChanging();
					this._tenQuyen = value;
					this.SendPropertyChanged("tenQuyen");
					this.OntenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="NVarChar(255)")]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this.OnmoTaChanging(value);
					this.SendPropertyChanging();
					this._moTa = value;
					this.SendPropertyChanged("moTa");
					this.OnmoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANQUYEN_NGUOIDUNG", Storage="_NGUOIDUNGs", ThisKey="maQuyen", OtherKey="maQuyen")]
		public EntitySet<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this._NGUOIDUNGs;
			}
			set
			{
				this._NGUOIDUNGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.PHANQUYEN = this;
		}
		
		private void detach_NGUOIDUNGs(NGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.PHANQUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGBAN")]
	public partial class PHONGBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPB;
		
		private string _tenPB;
		
		private string _moTa;
		
		private string _nguoiQuanLi;
		
		private string _diaChi;
		
		private string _soDienThoai;
		
		private EntitySet<CONGVAN> _CONGVANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPBChanging(string value);
    partial void OnmaPBChanged();
    partial void OntenPBChanging(string value);
    partial void OntenPBChanged();
    partial void OnmoTaChanging(string value);
    partial void OnmoTaChanged();
    partial void OnnguoiQuanLiChanging(string value);
    partial void OnnguoiQuanLiChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    #endregion
		
		public PHONGBAN()
		{
			this._CONGVANs = new EntitySet<CONGVAN>(new Action<CONGVAN>(this.attach_CONGVANs), new Action<CONGVAN>(this.detach_CONGVANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPB", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPB
		{
			get
			{
				return this._maPB;
			}
			set
			{
				if ((this._maPB != value))
				{
					this.OnmaPBChanging(value);
					this.SendPropertyChanging();
					this._maPB = value;
					this.SendPropertyChanged("maPB");
					this.OnmaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPB", DbType="NVarChar(255)")]
		public string tenPB
		{
			get
			{
				return this._tenPB;
			}
			set
			{
				if ((this._tenPB != value))
				{
					this.OntenPBChanging(value);
					this.SendPropertyChanging();
					this._tenPB = value;
					this.SendPropertyChanged("tenPB");
					this.OntenPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="NVarChar(255)")]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this.OnmoTaChanging(value);
					this.SendPropertyChanging();
					this._moTa = value;
					this.SendPropertyChanged("moTa");
					this.OnmoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiQuanLi", DbType="NVarChar(255)")]
		public string nguoiQuanLi
		{
			get
			{
				return this._nguoiQuanLi;
			}
			set
			{
				if ((this._nguoiQuanLi != value))
				{
					this.OnnguoiQuanLiChanging(value);
					this.SendPropertyChanging();
					this._nguoiQuanLi = value;
					this.SendPropertyChanged("nguoiQuanLi");
					this.OnnguoiQuanLiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(255)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="VarChar(15)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGBAN_CONGVAN", Storage="_CONGVANs", ThisKey="maPB", OtherKey="maPB")]
		public EntitySet<CONGVAN> CONGVANs
		{
			get
			{
				return this._CONGVANs;
			}
			set
			{
				this._CONGVANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONGVANs(CONGVAN entity)
		{
			this.SendPropertyChanging();
			entity.PHONGBAN = this;
		}
		
		private void detach_CONGVANs(CONGVAN entity)
		{
			this.SendPropertyChanging();
			entity.PHONGBAN = null;
		}
	}
}
#pragma warning restore 1591
